name: "Build and push 2"
on: 
  workflow_dispatch:
      inputs:
        TargetPlatformName:
          description: 'Target platform'
          type: string
          required: true
  pull_request:
    branches:
      - releases/**
      - master
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Build directory
        run: mkdir build

      - name: Run CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build

      - name: Archive build artifacts
        run: |
          zip -r output.zip build/MPMCQueueExample
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: output.zip
        if: startsWith(github.ref, 'refs/tags/')